version: "3.7"

services: 
  database: 
    image: postgres
    container_name: database_carteira
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=carteiraGustavo
      - POSTGRES_DB=CarteiraDeInvestimentos
    volumes:
      - pgdata:/data/postgres
    
  app: 
    build: .
    container_name: api_carteira
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
